name: 'AdoreMe Tech Image Setup action'
description: 'Sets the image to use'
inputs:
  tag:
    description: 'The tag of the image to use'
    required: false
    default: ''
  registry:
    description: 'Docker registry'
    required: true
    default: 'quay.io'
  repository:
    description: 'Docker repository'
    required: true
    default: 'adoreme'
  name:
    description: 'Docker image name'
    required: true
    default: 'nginx-fpm-alpine'
  config-location:
    description: 'Location of the config file'
    required: true
    default: './ci/config.yaml'
outputs:
  project-image:
    description: 'Fully qualified image address'
    value: '${{ steps.set-image-address.outputs.project-image }}'
  project-image-tag:
    description: 'Image tag'
    value: '${{ steps.set-image-address.outputs.project-image-tag }}'
runs:
  using: 'composite'
  steps:
    - name: 'Check config'
      id: check-config
      run: $GITHUB_ACTION_PATH/check-config.sh
      shell: bash
      env:
        INPUT_CONFIG_LOCATION: ${{ inputs.config-location }}
        INPUT_TAG: ${{ inputs.tag }}
    - name: 'Get image tag from CI config'
      id: project-image-config
      if: ${{ steps.check-config.outputs.get-tag-from-config == 'true' }}
      uses: jbutcher5/read-yaml@main
      with:
        file: ${{ inputs.config-location }}
        key-path: '["image-tag"]'
    - name: 'Set Image Address'
      id: set-image-address
      run: $GITHUB_ACTION_PATH/image.sh
      shell: bash
      env:
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_NAME: ${{ inputs.name }}
        IMAGE_TAG: ${{ steps.check-config.outputs.get-tag-from-config == 'true' && steps.project-image-config.outputs.data || inputs.tag }}
